### ISSUE TITLE
Cancelled Tasks And More

### ISSUE THREAD

**Issue by 702573n** [ivan-lednev/obsidian-task-archiver#17] opened 2022-07-16 03:42 UTC
Unfortunately this plugin doesn't support other checkmarks like:

```
- [-] Cancelled
- [>] Forwarded


Please add a <select> inside plugin settings tab to switch between the following archive rules:

Select 1: "Only completed tasks" >>> dv.current().file.tasks.filter(t => t.completed)
Select 2: "All checked tasks" >>> dv.current().file.tasks.filter(t => t.checked)
```

**Comment by ivan-lednev** [comment] 2022-09-30 09:40
Hello, @702573n,

Thank you for your input ❤️  The issue is addressed in 0.9.0.

**Closed by ivan-lednev** 2022-09-30 09:40 UTC
