### ISSUE TITLE
Moving uncompleted tasks: when / then rules with empty task status

### ISSUE THREAD

**Issue by nickynicolson** [ivan-lednev/obsidian-task-archiver#46] opened 2023-05-04 11:03 UTC
I'd like to be able to process (move) uncompleted tasks, i.e. those with a blank task status e.g.:
- [ ] mytask

Though I can specify a space character under task status in the "when" part of the rule (see image), uncompleted tasks are not moved.

![task-archiver-when-then](https://user-images.githubusercontent.com/3758694/236184839-6414960d-f17f-4bce-a26a-4f56422159ed.png)

I assume that tasks are pre-filtered and uncompleted ones not evaluated against rules - could we have an option to pass *all* task statuses to rules for processing please?

**Comment by ivan-lednev** [comment] 2023-05-04 15:10
Hi, @nickynicolson,

Thank you for your input! I'll handle this soon.

**Comment by ivan-lednev** [comment] 2023-05-07 12:09
Hi, @nickynicolson,

The issue is addressed in 0.23.2.

**Closed by ivan-lednev** 2023-05-07 12:09 UTC

**Comment by nickynicolson** [comment] 2023-05-09 10:20
Thanks Ivan, much appreciated
