### ISSUE TITLE
[Feature] automatically remove completed task in one specific file

### ISSUE THREAD

**Issue by imeed166** [ivan-lednev/obsidian-task-archiver#4] opened 2021-10-02 15:58 UTC
The ability to define a file in the setting where all the tasks that are completed are immediately (or after delay) removed automatically without any interaction from the user.

**Comment by ivan-lednev** [comment] 2021-11-02 18:09
Hello, @imeed166,
Thank you for your input.
The issue is partially addressed in [0.3.0](https://github.com/ivan-lednev/obsidian-task-archiver/releases/tag/0.3.0): now there is an option to define an archive file. You still need to trigger the command manually, but I'm planning to add automatic archiving in a future release.

**Comment by imeed166** [comment] 2021-11-02 19:23
> now there is an option to define an archive file.

Thank you, I've actually used this feature to make a macro to delete the new file after moving the completed tasks. So problem resolved.

> but I'm planning to add automatic archiving in a future release.

I'm so hyped for this, thank you for that too.

**Comment by imeed166** [comment] 2021-12-09 10:46
Hi again @ivan-lednev, I found a new way to delete tasks, and it requires interoperability between this plugin and [expiring notes](https://github.com/joerncodes/obsidian-expiring-notes).

Could you add an option for the created archive file, to include the below metadata upon creation? This way, expiring notes can recognize and delete it when the date is due.
```
expires: YYYY-MM-DD
```
Here is the [comment](https://github.com/joerncodes/obsidian-expiring-notes/issues/2#issuecomment-989624916) where your plugin was mentioned in expiring note's related discussion.

**Comment by ivan-lednev** [comment] 2022-03-31 14:42
Hello, @imeed166,

I've added a new command for deleting completed tasks in 0.4.0. I'm also going to track in a separate ticket the feature you mentioned above.

**Comment by ivan-lednev** [comment] 2022-04-01 10:31
The template issue is tracked here: #10

**Closed** 2022-04-01 10:31 UTC
