### ISSUE TITLE
Archive Heading Multiply

### ISSUE THREAD

**Issue by 702573N** [ivan-lednev/obsidian-task-archiver#12] opened 2022-04-24 03:50 UTC
Since the last update the archive heading multiplies when using levels >1. It seems that the plugin can't locate any existing archive headings defined inside the options panel. The depth of archive heading could cause the problem. I'm using level 2 "Archiv". Each time I'm calling the command a new archive heading added to the document and the completed tasks pushed below this new one. Level 1 archive headings working well.

**Comment by pds** [comment] 2022-05-11 16:19
Having this issue as well.  Thanks for the tip that level=1 does work!

**Comment by abonhote** [comment] 2022-08-11 06:50
Any chance this gets some treatment? Level 1 is reserved in my setup, so it works but it's not nice.

**Comment by pmagwene** [comment] 2022-10-15 01:23
Also experiencing this issue on Obsidian 1.0

**Comment by fakeharxy** [comment] 2022-11-11 12:10
just to say... me too! I thought it was how it was supposed to function, glad I found this so I can go to level 1 as a workaround

**Comment by ivan-lednev** [comment] 2022-11-12 11:54
Hello everyone! Thank you for your input! The issue is addressed in 0.9.1

**Closed by ivan-lednev** 2022-11-12 11:54 UTC
