### ISSUE TITLE
Archive indented items

### ISSUE THREAD

**Issue by Lulullia** [ivan-lednev/obsidian-task-archiver#14] opened 2022-05-05 12:23 UTC
Hi,
It seems the plugin only works with non-indented items. I put all of my tasks in a note under list items (or sometimes task items too) so right now this plugin is useless for me... When I run the command the plugin doesn't recognize any tasks and just shows a notice "No tasks to archive".

Is there a plan to support this feature? so I can know whether to find a workaround while waiting or just move to another plugin (the best thing about this plugin is the ability to archive directly to another file, so I'd prefer keeping it)

Thanks!

**Comment by ivan-lednev** [comment] 2022-05-10 08:46
Hello, @Lulullia 

Thank you for your input! The feature is going to be available in the next release.

**Comment by ivan-lednev** [comment] 2022-07-14 08:14
The issue is addressed in 0.6.0.

**Closed by ivan-lednev** 2022-07-14 08:14 UTC
